name: telegram_flutter
description: An fast compatible and fully customizable Telegram client for Flutter.
homepage: https://flutterchatting.herokuapp.com/
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mockito: ^5.2.0

  socket_io_client: ^2.0.0-beta.2
  animations: ^2.0.2
  get: ^4.6.1
  dio: ^4.0.4
  http_interceptor: ^1.0.2
  flutter_bloc: ^8.0.1
  build_runner: ^2.1.9
  flutter_gen_runner: ^4.1.6
  shared_preferences: ^2.0.15
  flutter_sticky_header: ^0.6.2
  lottie: ^1.3.0

  drift: ^1.6.0
  http: ^0.13.4 # used to load sqlite3 wasm files on the web
  sqlite3_flutter_libs: ^0.5.5
  sqlite3: ^1.7.0
  path_provider: ^2.0.9
  path: ^1.8.0
  idb_shim: ^2.0.1

  image_compression_flutter: ^1.0.2
  image: ^3.0.2
  flimer: ^1.0.1
#  flutter_webrtc: ^0.8.7
#  record: ^4.1.1
#  audio_session: ^0.1.6+1
#  just_audio_libwinmedia: ^0.0.4
#  just_audio: ^0.9.21
#  video_player: ^2.4.2
#  dart_vlc: ^0.0.2
#  flutter_neumorphic: ^3.2.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_gen: ^4.1.6
  drift_dev: ^1.4.0
  build_web_compilers: ^3.2.1
  http_mock_adapter: ^0.3.2

dependency_overrides:
  js: ^0.6.4 # temporarily added because sqlite3 depends on this, and flutter hasn't caught up yet.


flutter_gen:
  output: lib/common/gen/ # Optional (default: fluttermap/gen/)
  line_length: 80 # Optional (default: 80)

  assets:
    enabled: true
    package_parameter_enabled: false

  colors:
    inputs:
      - assets/color/colors.xml
  images:
    inputs:
      - assets/images/


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/b.png
    #if you want to build without json error comment line below
    - assets/tgs/

